### ISSUE TITLE
An error of google serper

### ISSUE THREAD

**Issue by RZFan525** [GAIR-NLP/factool#25]
An error is always raised when I use factool to detect kbqa task after finishing 1k times.
AttributeError: 'ClientResponseError' object has no attribute 'get'
<img width="1304" alt="image" src="https://github.com/GAIR-NLP/factool/assets/41265224/97d7790f-6229-4e1a-a2c3-10680ea29257">
I don't know whether is the problem of my SERPER_API_KEY.

**Comment by EthanC111** [comment]
@RZFan525 Thank you for bringing up this issue! Does this problem occur regardless of the response provided? If so, it's probably related to the API key issue. If I remember correctly, SERPER provides 2,500 free credits.

Let me know if you have more questions!

**Comment by RZFan525** [comment]
Thank you for your reply. I see my account. The reason is that I had spent all my credits.

**Comment by C-YEE00** [comment]
Do you need SCRAPER_API_KEY to detect kbqa tasks？

**Comment by steffichern** [comment]
Hi @C-YEE00, sorry for the late response. SCRAPER_API_KEY is only used for Scientific Literature Review tasks, not the KBQA tasks. Hope that helps!
