### ISSUE TITLE
###evaluate###kbqa###error

### ISSUE THREAD

**Issue by C-YEE00** [GAIR-NLP/factool#37]
Why is this error reported，i set the scraperapi='' when evaluate kbqa

requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='api.scraperapi.com', port=80): Max retries exceeded with url: /account?api_key=%27%27 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f33556f3490>, 'Connection to api.scraperapi.com timed out. (connect timeout=None)'))

**Comment by steffichern** [comment]
Hi, thank you for your interests in our work!

You will not need scraper API to evaluate KBQA. However, if the issue exists when you try to evaluate Scientific Literature Review, here are the possible reasons why this could happen:
1. Verify that you are using the correct URL and API key for ScraperAPI.
2. Scraper API service might be experiencing downtime or technical difficulties.
3. There might be a problem with how you've configured your request in terms of headers, parameters, or other settings.
4. Review your firewall or security software settings to ensure they aren't blocking your requests.

There might be other resources online that might help with debugging your issue. Hope this helps!

**Comment by C-YEE00** [comment]
If I don't set scraperapi='', I'll get an error
