### ISSUE TITLE
Where to download FactPrompts dataset?

### ISSUE THREAD

**Issue by zhimin-z** [GAIR-NLP/factool#38]
I cannot find any related sources...

**Comment by steffichern** [comment]
Hi! Thank you for your interests in our work!
The datasets can be found here: https://github.com/GAIR-NLP/factool/tree/main/datasets

Let us know if you have more questions!

**Comment by zhimin-z** [comment]
> Hi! Thank you for your interests in our work! The datasets can be found here: https://github.com/GAIR-NLP/factool/tree/main/datasets
> 
> Let us know if you have more questions!

Thanks! Are all of five folders fastprompt?
![image](https://github.com/GAIR-NLP/factool/assets/8592144/ab92f129-3fdc-4a28-af5c-d71bcb90cb4f)

**Comment by void-b583x2-NULL** [comment]
It appears to be that in the `knowledge_qa` folder are the 50 lines of FactPrompts. However, I also wonder that where the RoSE dataset locates. Is the dataset dynamically generated by the original [QAGS](https://github.com/W4ngatang/qags/) repo? Thx.

**Comment by zhimin-z** [comment]
> It appears to be that in the `knowledge_qa` folder are the 50 lines of FactPrompts. However, I also wonder that where the RoSE dataset locates. Is the dataset dynamically generated by the original [QAGS](https://github.com/W4ngatang/qags/) repo? Thx.

@steffichern Is that right?

**Comment by steffichern** [comment]
Hi, you can find the RoSE dataset here: https://huggingface.co/datasets/Salesforce/rose

Also, only the KBQA and scientific prompts are from FactPrompts. The code prompts are from HumanEval, and the math prompts are from GSMHard.

**Comment by qishenghu** [comment]
> Hi, you can find the RoSE dataset here: https://huggingface.co/datasets/Salesforce/rose
> 
> Also, only the KBQA and scientific prompts are from FactPrompts. The code prompts are from HumanEval, and the math prompts are from GSMHard.

<img width="527" alt="image" src="https://github.com/user-attachments/assets/20b77dab-3a82-4842-a5c3-bc0420e98482">
 
Hi, may i know which split is the 100 RoSE data used in the paper?
