### ISSUE TITLE
How many shots are used for evaluation of HumanEval?

### ISSUE THREAD

**Issue by zhimin-z** [GAIR-NLP/factool#39]
Is that 0-shot and 3-shot CoT?

**Comment by EthanC111** [comment]
Hi @zhimin-z . If you are referring to the Self-Check baselines, then yes. Please refer to https://github.com/GAIR-NLP/factool/blob/main/factool/utils/prompts/self_check.yaml

**Comment by zhimin-z** [comment]
> Hi @zhimin-z . If you are referring to the Self-Check baselines, then yes. Please refer to https://github.com/GAIR-NLP/factool/blob/main/factool/utils/prompts/self_check.yaml

Thanks for your quick replies
Are these evaluation results from 0-shot or 3-shot CoT?
![image](https://github.com/GAIR-NLP/factool/assets/8592144/9bdc68d7-9a61-460b-ae7d-99c627cd3396)

**Comment by EthanC111** [comment]
Hi @zhimin-z. These results were evaluated neither using 0-shot nor 3-shot. The results were evaluated using FacTool.
If you are referring to how the individual modules in FacTool are implemented, please refer to our prompts at https://github.com/GAIR-NLP/factool/tree/main/factool/utils/prompts

For some modules in certain tasks we did provide some demonstrations (e.g. query generation for KB-QA), while others we use 0-shot prompting.
